// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXB18ty7UimZR7fttZtzGvV9J7Eu_3B-Y',
    appId: '1:291564212728:web:ce37679faa4946c2ee460d',
    messagingSenderId: '291564212728',
    projectId: 'family-planner-9aff5',
    authDomain: 'family-planner-9aff5.firebaseapp.com',
    storageBucket: 'family-planner-9aff5.firebasestorage.app',
    measurementId: 'G-WF9B83X1HR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8L2ByaQo9pfxqrbRrQDb99-Ok1Y6vOW0',
    appId: '1:291564212728:android:e19ae2b21dd2c18dee460d',
    messagingSenderId: '291564212728',
    projectId: 'family-planner-9aff5',
    storageBucket: 'family-planner-9aff5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByEPXRmAbnP4-j6A5PFrMKY_ZjGDUsOYc',
    appId: '1:291564212728:ios:5eb19dc6041ec737ee460d',
    messagingSenderId: '291564212728',
    projectId: 'family-planner-9aff5',
    storageBucket: 'family-planner-9aff5.firebasestorage.app',
    iosBundleId: 'com.example.familyProductPlan',
  );
}
